version: '3.7'

# 컴퓨터들
services:
  # 컴퓨터이름
  my-backend:
    image: asia.gcr.io/f10-team01-server-372805/myproject-nestjs:9.4
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.prod
